export const emojiCategory = [
  {
    id: 'paopao',
    name: '泡泡',
    icon: '',
    textPattern: '@(${value})',
    type: 'image'
  },
  {
    id: 'alu',
    name: '阿鲁',
    icon: '',
    textPattern: '@[${value}]',
    type: 'image'
  },
  {
    id: 'emoji',
    name: 'emoji',
    icon: '',
    textPattern: '',
    type: 'emoticon'
  }
]

export const emojis = [
  { data: 'paopao/啊@2x.png', text: '啊', category: 'paopao' },
  { data: 'paopao/爱心@2x.png', text: '爱心', category: 'paopao' },
  { data: 'paopao/鄙视@2x.png', text: '鄙视', category: 'paopao' },
  { data: 'paopao/便便@2x.png', text: '便便', category: 'paopao' },
  { data: 'paopao/不高兴@2x.png', text: '不高兴', category: 'paopao' },
  { data: 'paopao/彩虹@2x.png', text: '彩虹', category: 'paopao' },
  { data: 'paopao/茶杯@2x.png', text: '茶杯', category: 'paopao' },
  { data: 'paopao/吃瓜@2x.png', text: '吃瓜', category: 'paopao' },
  { data: 'paopao/吃翔@2x.png', text: '吃翔', category: 'paopao' },
  { data: 'paopao/大拇指@2x.png', text: '大拇指', category: 'paopao' },
  { data: 'paopao/蛋糕@2x.png', text: '蛋糕', category: 'paopao' },
  { data: 'paopao/嘚瑟@2x.png', text: '嘚瑟', category: 'paopao' },
  { data: 'paopao/灯泡@2x.png', text: '灯泡', category: 'paopao' },
  { data: 'paopao/乖@2x.png', text: '乖', category: 'paopao' },
  { data: 'paopao/哈哈@2x.png', text: '哈哈', category: 'paopao' },
  { data: 'paopao/汗@2x.png', text: '汗', category: 'paopao' },
  { data: 'paopao/呵呵@2x.png', text: '呵呵', category: 'paopao' },
  { data: 'paopao/黑线@2x.png', text: '黑线', category: 'paopao' },
  { data: 'paopao/红领巾@2x.png', text: '红领巾', category: 'paopao' },
  { data: 'paopao/呼@2x.png', text: '呼', category: 'paopao' },
  { data: 'paopao/花心@2x.png', text: '花心', category: 'paopao' },
  { data: 'paopao/滑稽@2x.png', text: '滑稽', category: 'paopao' },
  { data: 'paopao/惊恐@2x.png', text: '惊恐', category: 'paopao' },
  { data: 'paopao/惊哭@2x.png', text: '惊哭', category: 'paopao' },
  { data: 'paopao/惊讶@2x.png', text: '惊讶', category: 'paopao' },
  { data: 'paopao/开心@2x.png', text: '开心', category: 'paopao' },
  { data: 'paopao/酷@2x.png', text: '酷', category: 'paopao' },
  { data: 'paopao/狂汗@2x.png', text: '狂汗', category: 'paopao' },
  { data: 'paopao/蜡烛@2x.png', text: '蜡烛', category: 'paopao' },
  { data: 'paopao/懒得理@2x.png', text: '懒得理', category: 'paopao' },
  { data: 'paopao/泪@2x.png', text: '泪', category: 'paopao' },
  { data: 'paopao/冷@2x.png', text: '冷', category: 'paopao' },
  { data: 'paopao/礼物@2x.png', text: '礼物', category: 'paopao' },
  { data: 'paopao/玫瑰@2x.png', text: '玫瑰', category: 'paopao' },
  { data: 'paopao/勉强@2x.png', text: '勉强', category: 'paopao' },
  { data: 'paopao/你懂的@2x.png', text: '你懂的', category: 'paopao' },
  { data: 'paopao/怒@2x.png', text: '怒', category: 'paopao' },
  { data: 'paopao/喷@2x.png', text: '喷', category: 'paopao' },
  { data: 'paopao/钱@2x.png', text: '钱', category: 'paopao' },
  { data: 'paopao/钱币@2x.png', text: '钱币', category: 'paopao' },
  { data: 'paopao/弱@2x.png', text: '弱', category: 'paopao' },
  { data: 'paopao/三道杠@2x.png', text: '三道杠', category: 'paopao' },
  { data: 'paopao/沙发@2x.png', text: '沙发', category: 'paopao' },
  { data: 'paopao/生气@2x.png', text: '生气', category: 'paopao' },
  { data: 'paopao/胜利@2x.png', text: '胜利', category: 'paopao' },
  { data: 'paopao/手纸@2x.png', text: '手纸', category: 'paopao' },
  { data: 'paopao/睡觉@2x.png', text: '睡觉', category: 'paopao' },
  { data: 'paopao/酸爽@2x.png', text: '酸爽', category: 'paopao' },
  { data: 'paopao/太开心@2x.png', text: '太开心', category: 'paopao' },
  { data: 'paopao/太阳@2x.png', text: '太阳', category: 'paopao' },
  { data: 'paopao/吐@2x.png', text: '吐', category: 'paopao' },
  { data: 'paopao/吐舌@2x.png', text: '吐舌', category: 'paopao' },
  { data: 'paopao/挖鼻@2x.png', text: '挖鼻', category: 'paopao' },
  { data: 'paopao/委屈@2x.png', text: '委屈', category: 'paopao' },
  { data: 'paopao/捂嘴笑@2x.png', text: '捂嘴笑', category: 'paopao' },
  { data: 'paopao/犀利@2x.png', text: '犀利', category: 'paopao' },
  { data: 'paopao/香蕉@2x.png', text: '香蕉', category: 'paopao' },
  { data: 'paopao/小乖@2x.png', text: '小乖', category: 'paopao' },
  { data: 'paopao/小红脸@2x.png', text: '小红脸', category: 'paopao' },
  { data: 'paopao/笑尿@2x.png', text: '笑尿', category: 'paopao' },
  { data: 'paopao/笑眼@2x.png', text: '笑眼', category: 'paopao' },
  { data: 'paopao/心碎@2x.png', text: '心碎', category: 'paopao' },
  { data: 'paopao/星星月亮@2x.png', text: '星星月亮', category: 'paopao' },
  { data: 'paopao/呀咩爹@2x.png', text: '呀咩爹', category: 'paopao' },
  { data: 'paopao/药丸@2x.png', text: '药丸', category: 'paopao' },
  { data: 'paopao/咦@2x.png', text: '咦', category: 'paopao' },
  { data: 'paopao/疑问@2x.png', text: '疑问', category: 'paopao' },
  { data: 'paopao/阴险@2x.png', text: '阴险', category: 'paopao' },
  { data: 'paopao/音乐@2x.png', text: '音乐', category: 'paopao' },
  { data: 'paopao/真棒@2x.png', text: '真棒', category: 'paopao' },
  { data: 'paopao/nico@2x.png', text: 'nico', category: 'paopao' },
  { data: 'paopao/OK@2x.png', text: 'OK', category: 'paopao' },
  { data: 'paopao/what@2x.png', text: 'what', category: 'paopao' },
  { data: 'paopao/doge@2x.png', text: 'doge', category: 'paopao' },
  { data: 'paopao/原谅她@2x.png', text: '原谅她', category: 'paopao' },
  { data: 'alu/暗地观察@2x.png', text: '暗地观察', category: 'alu' },
  { data: 'alu/便便@2x.png', text: '便便', category: 'alu' },
  { data: 'alu/不出所料@2x.png', text: '不出所料', category: 'alu' },
  { data: 'alu/不高兴@2x.png', text: '不高兴', category: 'alu' },
  { data: 'alu/不说话@2x.png', text: '不说话', category: 'alu' },
  { data: 'alu/抽烟@2x.png', text: '抽烟', category: 'alu' },
  { data: 'alu/呲牙@2x.png', text: '呲牙', category: 'alu' },
  { data: 'alu/大囧@2x.png', text: '大囧', category: 'alu' },
  { data: 'alu/得意@2x.png', text: '得意', category: 'alu' },
  { data: 'alu/愤怒@2x.png', text: '愤怒', category: 'alu' },
  { data: 'alu/尴尬@2x.png', text: '尴尬', category: 'alu' },
  { data: 'alu/高兴@2x.png', text: '高兴', category: 'alu' },
  { data: 'alu/鼓掌@2x.png', text: '鼓掌', category: 'alu' },
  { data: 'alu/观察@2x.png', text: '观察', category: 'alu' },
  { data: 'alu/害羞@2x.png', text: '害羞', category: 'alu' },
  { data: 'alu/汗@2x.png', text: '汗', category: 'alu' },
  { data: 'alu/黑线@2x.png', text: '黑线', category: 'alu' },
  { data: 'alu/欢呼@2x.png', text: '欢呼', category: 'alu' },
  { data: 'alu/击掌@2x.png', text: '击掌', category: 'alu' },
  { data: 'alu/惊喜@2x.png', text: '惊喜', category: 'alu' },
  { data: 'alu/看不见@2x.png', text: '看不见', category: 'alu' },
  { data: 'alu/看热闹@2x.png', text: '看热闹', category: 'alu' },
  { data: 'alu/抠鼻@2x.png', text: '抠鼻', category: 'alu' },
  { data: 'alu/口水@2x.png', text: '口水', category: 'alu' },
  { data: 'alu/哭泣@2x.png', text: '哭泣', category: 'alu' },
  { data: 'alu/狂汗@2x.png', text: '狂汗', category: 'alu' },
  { data: 'alu/蜡烛@2x.png', text: '蜡烛', category: 'alu' },
  { data: 'alu/脸红@2x.png', text: '脸红', category: 'alu' },
  { data: 'alu/内伤@2x.png', text: '内伤', category: 'alu' },
  { data: 'alu/喷水@2x.png', text: '喷水', category: 'alu' },
  { data: 'alu/喷血@2x.png', text: '喷血', category: 'alu' },
  { data: 'alu/期待@2x.png', text: '期待', category: 'alu' },
  { data: 'alu/亲亲@2x.png', text: '亲亲', category: 'alu' },
  { data: 'alu/傻笑@2x.png', text: '傻笑', category: 'alu' },
  { data: 'alu/扇耳光@2x.png', text: '扇耳光', category: 'alu' },
  { data: 'alu/深思@2x.png', text: '深思', category: 'alu' },
  { data: 'alu/锁眉@2x.png', text: '锁眉', category: 'alu' },
  { data: 'alu/投降@2x.png', text: '投降', category: 'alu' },
  { data: 'alu/吐@2x.png', text: '吐', category: 'alu' },
  { data: 'alu/吐舌@2x.png', text: '吐舌', category: 'alu' },
  { data: 'alu/吐血倒地@2x.png', text: '吐血倒地', category: 'alu' },
  { data: 'alu/无奈@2x.png', text: '无奈', category: 'alu' },
  { data: 'alu/无所谓@2x.png', text: '无所谓', category: 'alu' },
  { data: 'alu/无语@2x.png', text: '无语', category: 'alu' },
  { data: 'alu/喜极而泣@2x.png', text: '喜极而泣', category: 'alu' },
  { data: 'alu/献花@2x.png', text: '献花', category: 'alu' },
  { data: 'alu/献黄瓜@2x.png', text: '献黄瓜', category: 'alu' },
  { data: 'alu/想一想@2x.png', text: '想一想', category: 'alu' },
  { data: 'alu/小怒@2x.png', text: '小怒', category: 'alu' },
  { data: 'alu/小眼睛@2x.png', text: '小眼睛', category: 'alu' },
  { data: 'alu/邪恶@2x.png', text: '邪恶', category: 'alu' },
  { data: 'alu/咽气@2x.png', text: '咽气', category: 'alu' },
  { data: 'alu/阴暗@2x.png', text: '阴暗', category: 'alu' },
  { data: 'alu/赞一个@2x.png', text: '赞一个', category: 'alu' },
  { data: 'alu/长草@2x.png', text: '长草', category: 'alu' },
  { data: 'alu/中刀@2x.png', text: '中刀', category: 'alu' },
  { data: 'alu/中枪@2x.png', text: '中枪', category: 'alu' },
  { data: 'alu/中指@2x.png', text: '中指', category: 'alu' },
  { data: 'alu/肿包@2x.png', text: '肿包', category: 'alu' },
  { data: 'alu/皱眉@2x.png', text: '皱眉', category: 'alu' },
  { data: 'alu/装大款@2x.png', text: '装大款', category: 'alu' },
  { data: 'alu/坐等@2x.png', text: '坐等', category: 'alu' },
  { data: '😀', text: '😀', category: 'emoji' },
  { data: '😁', text: '😁', category: 'emoji' },
  { data: '😂', text: '😂', category: 'emoji' },
  { data: '😃', text: '😃', category: 'emoji' },
  { data: '😄', text: '😄', category: 'emoji' },
  { data: '😅', text: '😅', category: 'emoji' },
  { data: '😆', text: '😆', category: 'emoji' },
  { data: '😇', text: '😇', category: 'emoji' },
  { data: '😈', text: '😈', category: 'emoji' },
  { data: '😉', text: '😉', category: 'emoji' },
  { data: '😊', text: '😊', category: 'emoji' },
  { data: '😋', text: '😋', category: 'emoji' },
  { data: '😌', text: '😌', category: 'emoji' },
  { data: '😍', text: '😍', category: 'emoji' },
  { data: '😎', text: '😎', category: 'emoji' },
  { data: '😏', text: '😏', category: 'emoji' },
  { data: '😐', text: '😐', category: 'emoji' },
  { data: '😑', text: '😑', category: 'emoji' },
  { data: '😒', text: '😒', category: 'emoji' },
  { data: '😓', text: '😓', category: 'emoji' },
  { data: '😔', text: '😔', category: 'emoji' },
  { data: '😕', text: '😕', category: 'emoji' },
  { data: '😖', text: '😖', category: 'emoji' },
  { data: '😗', text: '😗', category: 'emoji' },
  { data: '😘', text: '😘', category: 'emoji' },
  { data: '😙', text: '😙', category: 'emoji' },
  { data: '😚', text: '😚', category: 'emoji' },
  { data: '😛', text: '😛', category: 'emoji' },
  { data: '😜', text: '😜', category: 'emoji' },
  { data: '😝', text: '😝', category: 'emoji' },
  { data: '😞', text: '😞', category: 'emoji' },
  { data: '😟', text: '😟', category: 'emoji' },
  { data: '😠', text: '😠', category: 'emoji' },
  { data: '😡', text: '😡', category: 'emoji' },
  { data: '😢', text: '😢', category: 'emoji' },
  { data: '😣', text: '😣', category: 'emoji' },
  { data: '😤', text: '😤', category: 'emoji' },
  { data: '😥', text: '😥', category: 'emoji' },
  { data: '😦', text: '😦', category: 'emoji' },
  { data: '😧', text: '😧', category: 'emoji' },
  { data: '👆', text: '👆', category: 'emoji' },
  { data: '👇', text: '👇', category: 'emoji' },
  { data: '👈', text: '👈', category: 'emoji' },
  { data: '👉', text: '👉', category: 'emoji' },
  { data: '👊', text: '👊', category: 'emoji' },
  { data: '👋', text: '👋', category: 'emoji' },
  { data: '👌', text: '👌', category: 'emoji' },
  { data: '👍', text: '👍', category: 'emoji' },
  { data: '👎', text: '👎', category: 'emoji' },
  { data: '👏', text: '👏', category: 'emoji' },
  { data: '👐', text: '👐', category: 'emoji' },
  { data: '⚽', text: '⚽', category: 'emoji' },
  { data: '⚾', text: '⚾', category: 'emoji' },
  { data: '🎽', text: '🎽', category: 'emoji' },
  { data: '🎾', text: '🎾', category: 'emoji' },
  { data: '🎿', text: '🎿', category: 'emoji' },
  { data: '🏀', text: '🏀', category: 'emoji' },
  { data: '🏁', text: '🏁', category: 'emoji' },
  { data: '🏂', text: '🏂', category: 'emoji' },
  { data: '🏃', text: '🏃', category: 'emoji' },
  { data: '🏄', text: '🏄', category: 'emoji' },
  { data: '🏆', text: '🏆', category: 'emoji' },
  { data: '🏇', text: '🏇', category: 'emoji' },
  { data: '🏈', text: '🏈', category: 'emoji' },
  { data: '🏉', text: '🏉', category: 'emoji' },
  { data: '🏊', text: '🏊', category: 'emoji' },
  { data: '🐭', text: '🐭', category: 'emoji' },
  { data: '🐮', text: '🐮', category: 'emoji' },
  { data: '🐯', text: '🐯', category: 'emoji' },
  { data: '🐰', text: '🐰', category: 'emoji' },
  { data: '🐱', text: '🐱', category: 'emoji' },
  { data: '🐲', text: '🐲', category: 'emoji' },
  { data: '🐳', text: '🐳', category: 'emoji' },
  { data: '🐴', text: '🐴', category: 'emoji' },
  { data: '🐵', text: '🐵', category: 'emoji' },
  { data: '🐶', text: '🐶', category: 'emoji' },
  { data: '🐷', text: '🐷', category: 'emoji' },
  { data: '🐸', text: '🐸', category: 'emoji' },
  { data: '🐹', text: '🐹', category: 'emoji' },
  { data: '🐺', text: '🐺', category: 'emoji' },
  { data: '🐻', text: '🐻', category: 'emoji' },
  { data: '🐼', text: '🐼', category: 'emoji' },
  { data: '🐽', text: '🐽', category: 'emoji' }
]
